{
 "title": "Verdaccio",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Pods",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"verdaccio\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Last Terminated Exit Code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_exitcode{namespace=\"verdaccio\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"verdaccio\"}",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"verdaccio/verdaccio\"} |~ \"error---\" [1m])) or vector(0)"
    }
   ]
  },
  {
   "title": "Recent Errors",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"verdaccio/verdaccio\"} |~ \"(error: |error--- |http <-- 40|http <-- 50|info <-- 40|info <-- 50)\""
    }
   ]
  },
  {
   "title": "New Verdaccio Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"verdaccio/verdaccio\"} |= \"the user\" |= \"has been added\" [5m])) or vector(0)\n"
    }
   ]
  },
  {
   "title": "Recently added users",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "{job=\"verdaccio/verdaccio\"} |= \"the user\" |= \"has been added\""
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Requests Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"verdaccio\", image!=\"\"}[$__rate_interval])) / sum by (pod) (kube_pod_container_resource_requests{namespace=\"verdaccio\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Limits Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"verdaccio\", image!=\"\"}[$__rate_interval])) / sum by(pod) (kube_pod_container_resource_limits{namespace=\"verdaccio\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Requests Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"verdaccio\", image!=\"\"}) / sum by(pod) (kube_pod_container_resource_requests{namespace=\"verdaccio\", resource=\"memory\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Limits Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"verdaccio\", image!=\"\"}) / sum by(pod) (kube_pod_container_resource_limits{namespace=\"verdaccio\", resource=\"memory\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Resources by pod",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"verdaccio\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"verdaccio\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"verdaccio\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{namespace=\"verdaccio\", resource=\"memory\"})"
    },
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"verdaccio\", image!=\"\", container!=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"verdaccio\", image!=\"\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"verdaccio\", image!=\"\", container!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"verdaccio\", image!=\"\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Network - Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{namespace=\"verdaccio\"}[$__rate_interval]))",
     "legendFormat": "Received-{{pod}}"
    },
    {
     "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{namespace=\"verdaccio\"}[$__rate_interval]))",
     "legendFormat": "Transmitted-{{pod}}"
    }
   ]
  },
  {
   "title": "Network - Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_receive_packets_total{namespace=\"verdaccio\"}[$__rate_interval]))",
     "legendFormat": "Received-{{pod}}"
    },
    {
     "expr": "sum by(pod) (rate(container_network_transmit_packets_total{namespace=\"verdaccio\"}[$__rate_interval]))",
     "legendFormat": "Transmitted-{{pod}}"
    }
   ]
  }
 ]
}